name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: 🎯 Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 💡 Proposed Solution
      description: Describe the solution you'd like
      placeholder: I think we should add...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 🔄 Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: Instead of..., we could also...

  - type: dropdown
    id: component
    attributes:
      label: 🎯 Component
      description: Which part of the application would this affect?
      options:
        - Frontend UI
        - Backend API
        - Database Schema
        - Authentication
        - Resume Parser
        - Job Search
        - AI/ML Features
        - Blockchain
        - Documentation
        - Testing
        - DevOps/CI/CD
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: ⚡ Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Needed for core functionality
        - Critical - Blocking issue
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: ✨ Benefits
      description: What benefits will this feature provide?
      placeholder: |
        - Improved user experience
        - Better performance
        - Enhanced security
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: 🎨 Mockups/Examples
      description: Add mockups, screenshots, or examples if applicable
      placeholder: Drag and drop images here, or provide links

  - type: textarea
    id: implementation
    attributes:
      label: 🔧 Implementation Ideas
      description: Do you have any ideas on how this could be implemented?
      placeholder: This could be implemented by...

  - type: textarea
    id: additional
    attributes:
      label: 📌 Additional Context
      description: Add any other context about the feature request
      placeholder: Similar features exist in...

  - type: checkboxes
    id: checklist
    attributes:
      label: ✅ Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
        - label: I can provide additional mockups or specifications if needed
          required: false
